### PR TITLE
fix: Rename FIToFICstmrCdt to FIToFICstmrCdtTrf

### PR DESCRIPTION
**Pull request by Sandy-at-Tazama**
https://github.com/frmscoe/postman/issues/61 

Rename FIToFICstmrCdt to FIToFICstmrCdtTrf

### CODE REVIEW

**Comment by Sandy-at-Tazama** [comment]
End to end test required

**Review by Justus-at-Tazama — APPROVED** [review]

**Comment by Justus-at-Tazama** [comment]
Assuming the change is only to update the indexes for now. Merging this into `dev` so that we can also update the postman tests themselves.

**Comment by Justus-at-Tazama** [comment]
image

**Comment by Justus-at-Tazama** [comment]
image

**Pull request merged**
